using System;
using System.Collections.Generic;
using System.IO;
using Newtonsoft.Json.Linq;
using Yukino.VRChatAgent;

// Core backend fixture, not Unity or native-handler execution. Uses real files.
sealed class WriteFixture : IMaterialCandidateBackend, IDisposable
{
 public readonly string Root = Path.Combine(Path.GetTempPath(), "vragent-write-"+Guid.NewGuid().ToString("N"));
 public int Writes; public Action DuringWrite, DuringRestore, DuringCheckpoint, DuringRead; public bool ThrowAfterWrite, UnknownAfterWrite;
 public WriteFixture(){Directory.CreateDirectory(Root); Put("Assets/source.mat", "original");}
 string PathOf(string key)=>Path.Combine(Root,key.Replace('/', '_'));
 public void Put(string key,string value)=>File.WriteAllText(PathOf(key),value);
 public string Value(string key)=>File.Exists(PathOf(key))?File.ReadAllText(PathOf(key)):"absent";
 public JObject Capture(JObject manifest, JObject command) {
  if(UnknownAfterWrite && Writes>0)throw new IOException("private-detail");
  var s=new JObject{["asset:"+(string)manifest["source"]]=Value((string)manifest["source"]),["asset:"+(string)manifest["candidate"]]=Value((string)manifest["candidate"]),["dependency:texture"] = Value("texture"),["callback_inventory"]="none"};
  foreach(JObject host in (JArray)manifest["references"])s["host:"+(string)host["renderer"]]=Value((string)host["renderer"]);
  return s;
 }
 public object Checkpoint(JObject manifest, JObject command){var value=Value(command["action"].ToString()=="reference"?(string)command["renderer"]:(string)manifest["candidate"]);DuringCheckpoint?.Invoke();return value;}
 public JObject Apply(JObject manifest,JObject command){Writes++;string a=(string)command["action"];Put(a=="reference"?(string)command["renderer"]:(string)manifest["candidate"],a=="copy"?Value((string)manifest["source"]):command["value"]?.ToString()??(string)manifest["candidate"]);DuringWrite?.Invoke();if(ThrowAfterWrite)throw new IOException("secret-path");return new JObject{["success"]=true};}
 public JObject Read(JObject manifest){var value=new JObject{["material"]=Value((string)manifest["candidate"])};DuringRead?.Invoke();return value;}
 public void Restore(JObject manifest,JObject command,object checkpoint){Put(command["action"].ToString()=="reference"?(string)command["renderer"]:(string)manifest["candidate"],(string)checkpoint);DuringRestore?.Invoke();}
 public void Dispose(){Directory.Delete(Root,true);}
}
static class WriteCases
{
 static void Assert(bool ok,string why){if(!ok)throw new Exception(why);}
 static JObject Request(string kind,JObject body=null,string plan="",string task="task-A")=>new JObject{["protocol"]=1,["kind"]=kind,["project_id"]="project-A",["connection_id"]="connection-A",["client_id"]="client-A",["task_id"]=task,["plan_id"]=plan,["body"]=body??new JObject()};
 static JObject Manifest()=>new JObject{["source"]="Assets/source.mat",["candidate"]="Assets/candidate.mat",["operations"]=new JArray("copy","edit"),["references"]=new JArray(),["ttl_seconds"]=300};
 static MaterialCandidateGate Gate(WriteFixture f)=>new MaterialCandidateGate(()=>100,()=>"project-A",()=>"connection-A",f);
 static string Prepare(MaterialCandidateGate gate,JObject m=null){var r=gate.Dispatch(Request("prepare",m??Manifest()));Assert((bool?)r["success"]==true,r.ToString());string id=(string)r["data"]["plan_id"];Assert(gate.Approve(id,(string)r["data"]["digest"]),"local approval");return id;}
 static JObject Execute(MaterialCandidateGate gate,string id,string action,string value=null)=>gate.Dispatch(Request("execute",new JObject{["action"]=action,["arguments"]=action=="edit"?new JObject{["property"]="_AnyShaderProperty",["value"]=value}:new JObject()},id));
 static void Trace(){using var f=new WriteFixture();var gate=Gate(f);gate.SetCapability("copy",true);gate.SetCapability("edit",true);string id=Prepare(gate);var copied=Execute(gate,id,"copy");Assert((bool?)copied["success"]==true,copied.ToString());Assert(f.Value("Assets/source.mat")=="original","original changed");Assert(f.Value("Assets/candidate.mat")=="original","copy not created");var edited=Execute(gate,id,"edit","0.6");Assert((bool?)edited["success"]==true,edited.ToString());Assert((string)edited["data"]["transaction"]["outcome"]=="changed","missing actual report");Assert((string)edited["data"]["readback"]["material"]=="0.6","readback missing");}
 static void PartialFailure(){using var f=new WriteFixture();var g=Gate(f);g.SetCapability("copy",true);g.SetCapability("edit",true);string id=Prepare(g);Execute(g,id,"copy");f.ThrowAfterWrite=true;var r=Execute(g,id,"edit","0.9");Assert((bool?)r["success"]==false,"failure promoted");Assert((string)r["data"]["transaction"]?["outcome"]=="changed","partial mutation must be reported");Assert(!r.ToString().Contains("secret-path"),"exception leak");Assert(f.Value("Assets/candidate.mat")=="0.9","failure rolled back");Assert(g.LocalPlans().Count==0,"failure did not revoke");}
 static void SideEffect(){using var f=new WriteFixture();var g=Gate(f);g.SetCapability("copy",true);string id=Prepare(g,new JObject{["source"]="Assets/source.mat",["candidate"]="Assets/candidate.mat",["operations"]=new JArray("copy"),["references"]=new JArray(),["ttl_seconds"]=300});f.DuringWrite=()=>f.Put("texture","unexpected");var r=Execute(g,id,"copy");Assert((bool?)r["success"]==false,"side-effect silently accepted");Assert((string)r["error"]=="unexpected_side_effect","side-effect not classified");Assert((string)r["data"]["transaction"]["side_effects"][0]=="dependency:texture","side-effect missing");Assert(f.Value("texture")=="unexpected","automatic rollback");}
 static void Reference(){using var f=new WriteFixture();f.Put("renderer-1","old-material");var g=Gate(f);g.SetCapability("copy",true);g.SetCapability("edit",true);g.SetCapability("reference",true);var m=Manifest();((JArray)m["operations"]).Add("reference");((JArray)m["references"]).Add(new JObject{["renderer"]="renderer-1",["slot"]=0});string id=Prepare(g,m);Execute(g,id,"copy");var r=g.Dispatch(Request("execute",new JObject{["action"]="reference",["arguments"]=new JObject{["renderer"]="renderer-1",["slot"]=0}},id));Assert((bool?)r["success"]==true,r.ToString());Assert(f.Value("renderer-1")=="Assets/candidate.mat","reference not switched");var denied=g.Dispatch(Request("execute",new JObject{["action"]="reference",["arguments"]=new JObject{["renderer"]="renderer-other",["slot"]=0}},id));Assert((string)denied["error"]=="reference_not_approved","unapproved host allowed");Assert(f.Value("renderer-other")=="absent","other host changed");}
 static void Withdraw(){using var f=new WriteFixture();var g=Gate(f);g.SetCapability("copy",true);g.SetCapability("edit",true);string id=Prepare(g);Execute(g,id,"copy");var r=Execute(g,id,"edit","0.8");string tx=(string)r["data"]["transaction"]["id"];g.Dispatch(Request("stop",plan:id));Assert(f.Value("Assets/candidate.mat")=="0.8","stop rolled back");var undone=g.Withdraw(tx);Assert((bool?)undone["success"]==true,undone.ToString());Assert(f.Value("Assets/candidate.mat")=="original","not restored");Assert(f.Value("Assets/source.mat")=="original","source modified");}
 static void StoppedInFlight(){using var f=new WriteFixture();var g=Gate(f);g.SetCapability("copy",true);g.SetCapability("edit",true);string id=Prepare(g);f.DuringWrite=()=>g.StopAll("local stop");var r=Execute(g,id,"copy");Assert((string)r["data"]["status"]=="stopped_after_safe_point","inflight stop not reported");Assert((bool?)r["data"]["grant_active"]==false,"grant appears active");Assert(f.Value("Assets/candidate.mat")=="original","stop rollback");var s=g.Dispatch(Request("status",plan:id));Assert((bool?)s["success"]==true,s.ToString());Assert(((JArray)s["data"]["transactions"]).Count==1,"stopped transaction report lost");}
 static void ExpandedReference(){using var f=new WriteFixture();var g=Gate(f);g.SetCapability("copy",true);g.SetCapability("edit",true);string old=Prepare(g);Execute(g,old,"copy");Execute(g,old,"edit","0.4");g.SetCapability("reference",true);var m=Manifest();m["operations"]=new JArray("edit","reference");m["references"]=new JArray(new JObject{["renderer"]="renderer-later",["slot"]=0});string id=Prepare(g,m);Assert(id!=old,"plan not replaced");var result=g.Dispatch(Request("execute",new JObject{["action"]="reference",["arguments"]=new JObject{["renderer"]="renderer-later",["slot"]=0}},id));Assert((bool?)result["success"]==true,result.ToString());Assert(f.Value("Assets/candidate.mat")=="0.4","candidate reset");var late=g.Dispatch(Request("stop",plan:old));Assert((bool?)late["success"]==false && g.LocalPlans().Count==1,"late stop revoked new plan");}
 static void UserEditProtected(){using var f=new WriteFixture();var g=Gate(f);g.SetCapability("copy",true);g.SetCapability("edit",true);string id=Prepare(g);Execute(g,id,"copy");var r=Execute(g,id,"edit","0.7");f.Put("Assets/candidate.mat","user-edit");var undo=g.Withdraw((string)r["data"]["transaction"]["id"]);Assert((string)undo["error"]=="postimage_conflict" && f.Value("Assets/candidate.mat")=="user-edit","user edit overwritten");}
 static void Unknown(){using var f=new WriteFixture();var g=Gate(f);g.SetCapability("copy",true);g.SetCapability("edit",true);string id=Prepare(g);f.UnknownAfterWrite=true;var r=Execute(g,id,"copy");Assert((string)r["data"]["transaction"]["outcome"]=="unknown" && (bool?)r["success"]==false,"uncertain state hidden");}
 static void DependencyConflict(){using var f=new WriteFixture();var g=Gate(f);g.SetCapability("copy",true);g.SetCapability("edit",true);string id=Prepare(g);f.Put("texture","external-edit");var r=Execute(g,id,"copy");Assert((string)r["error"]=="relevant_evidence_changed" && f.Writes==0,"dependency conflict not blocked");}
 static void DefaultClosed(){using var f=new WriteFixture();var g=Gate(f);var r=g.Dispatch(Request("prepare",Manifest()));Assert((bool?)r["success"]==false && f.Writes==0,"default open");g.SetCapability("copy",true);g.SetCapability("edit",true);var pending=g.Dispatch(Request("prepare",Manifest()));var e=Execute(g,(string)pending["data"]["plan_id"],"copy");Assert((string)e["error"]=="local_approval_required" && f.Writes==0,"remote approval");}
 static void ForeignExisting(){using var f=new WriteFixture();var g=Gate(f);g.SetCapability("edit",true);f.Put("Assets/candidate.mat","existing-user-file");var m=Manifest();m["operations"]=new JArray("edit");var r=g.Dispatch(Request("prepare",m));Assert((string)r["error"]=="candidate_provenance_conflict","arbitrary existing file treated as candidate");}
 static void WireStrict(){using var f=new WriteFixture();var g=Gate(f);g.SetCapability("copy",true);g.SetCapability("edit",true);string id=Prepare(g);var bad=Request("execute",new JObject{["action"]="copy",["arguments"]=new JObject(),["approved"]=true},id);Assert((string)g.Dispatch(bad)["error"]=="unexpected_fields" && f.Writes==0,"schema widened");}
 static void WithdrawSideEffects(){using var f=new WriteFixture();var g=Gate(f);g.SetCapability("copy",true);g.SetCapability("edit",true);string id=Prepare(g);Execute(g,id,"copy");var r=Execute(g,id,"edit","0.7");f.DuringRestore=()=>f.Put("texture","restore-side-effect");var undone=g.Withdraw((string)r["data"]["transaction"]["id"]);Assert((bool?)undone["success"]==false && (string)undone["error"]=="withdraw_side_effect","withdraw side-effect hidden");Assert((string)undone["data"]["direct_outcome"]=="withdrawn","direct outcome not reported");Assert(f.Value("texture")=="restore-side-effect","side effects rolled back");}
 static void CheckpointRace(){using var f=new WriteFixture();var g=Gate(f);g.SetCapability("copy",true);g.SetCapability("edit",true);string id=Prepare(g);f.DuringCheckpoint=()=>f.Put("Assets/source.mat","user-change");var r=Execute(g,id,"copy");Assert((bool?)r["success"]==false && f.Writes==0,"checkpoint race overwrote newer state");}
 static void ForeignPrepareDoesNotRevoke(){using var f=new WriteFixture();var g=Gate(f);g.SetCapability("copy",true);g.SetCapability("edit",true);string id=Prepare(g);var foreign=Request("prepare",Manifest());foreign["client_id"]="other-client";var r=g.Dispatch(foreign);Assert((string)r["error"]=="project_write_busy" && g.LocalPlans().Count==1,"foreign prepare revoked owner");Assert((bool?)Execute(g,id,"copy")["success"]==true,"owner lost grant");}
 static void FinalCaptureFailure(){using var f=new WriteFixture();var g=Gate(f);g.SetCapability("copy",true);g.SetCapability("edit",true);string id=Prepare(g);f.DuringRead=()=>f.UnknownAfterWrite=true;var r=Execute(g,id,"copy");Assert((bool?)r["success"]==false && r["data"]["transaction"]!=null,"final capture erased transaction report");Assert(g.LocalTransactions().Count==1,"journal lost");}
 public static int Main(){try{Trace();Console.WriteLine("PASS WC001 copy_file_edit_readback");PartialFailure();Console.WriteLine("PASS WC002 partial_failure_preserves_reports");SideEffect();Console.WriteLine("PASS WC003 dependency_side_effect_report");Reference();Console.WriteLine("PASS WC004 exact_reference_host");Withdraw();Console.WriteLine("PASS WC005 explicit_local_withdraw");StoppedInFlight();Console.WriteLine("PASS WC006 inflight_stop_reports");ExpandedReference();Console.WriteLine("PASS WC007 separately_approved_reference_extension");UserEditProtected();Console.WriteLine("PASS WC008 postimage_protects_user");Unknown();Console.WriteLine("PASS WC009 unknown_is_not_unchanged");DependencyConflict();Console.WriteLine("PASS WC010 dependency_conflict");DefaultClosed();Console.WriteLine("PASS WC011 local_capability_and_approval");ForeignExisting();Console.WriteLine("PASS WC012 candidate_provenance");WireStrict();Console.WriteLine("PASS WC013 strict_write_schema");WithdrawSideEffects();Console.WriteLine("PASS WC014 withdraw_side_effect_report");CheckpointRace();Console.WriteLine("PASS WC015 checkpoint_revalidation");ForeignPrepareDoesNotRevoke();Console.WriteLine("PASS WC016 foreign_plan_cannot_revoke_owner");FinalCaptureFailure();Console.WriteLine("PASS WC017 final_capture_preserves_report");return 0;}catch(Exception e){Console.WriteLine("FAIL "+e);return 1;}}
}
